### ISSUE TITLE
How-To setup telemetry using Prometheus and Grafana?

### ISSUE THREAD

**Issue by taitruong** [cosmos/relayer#1288]
Hi, trying to setup a dashboard for my relayer using Prometheus and Grafana. Are there any resources for setting this up?
I only found a comment about using `http://localhost:5183/relayer/metrics` for Prometheus.

I found a guide for Hermes for setting up Prometheus, Grafana, Loki and Promtail [here](https://hermes.informal.systems/tutorials/production/setup-grafana.html).

As far as I understand Grafana is used to visualise logs (by using Loki) and metrics (by using Prometheus). Seems like these steps are required:

- assuming logs must be in file and proper format (prob: `--log-format logfmt`)
- setup Promtail for shipping local log to private Grafana Loki instance
- setup Grafana e.g. with port 3000, add 2 data sources for Loki and Prometheus
- setup Grafana dashboard

Only thing I'm not sure where  `http://localhost:5183/relayer/metrics` comes into place during setup.

Anything I'm missing here?

**Comment by jtieri** [comment]
cc @agouin @AntiTyping @danbryan

**Comment by danbryan** [comment]
i don't have a full write up for this, but here is a few snipits from my relayer metrics.

enable metrics on the rly process
```
--debug-addr 0.0.0.0:7597
```


create job in prometheus-config.yaml

```
      - job_name:       'relayer-kujira'
        metrics_path: /relayer/metrics
        static_configs:
          - targets: [
              "relayer-metrics--mainnet.customer-kujira:7597"
            ]
            labels: {"network": kujira}
        relabel_configs:
          - target_label: job
            replacement: "relayer"
```

build a dashboard on this info.  For example, this is one i use for watching the client expiration's.

[client-expirations.json](https://github.com/cosmos/relayer/files/12873687/client-expirations.json)

![image](https://github.com/cosmos/relayer/assets/807940/956e6a57-f243-4301-a796-9cdc38e81582)
