### ISSUE TITLE
transact channel error: got ics721-1, expected ics20-1: invalid ICS20 version

### ISSUE THREAD

**Issue by taitruong** [cosmos/relayer#1299]
I'm getting errors for creating a channel for our ics721 contracts.

I'm able to create client, connection and channel using:
`rly transact link junotestnet-stargazetestnet --override --log-format json -v ics721-1 --src-port wasm.juno1uvflayc34fs9r3tzcausztks2058ecpt5kqtzf3sz5kwnu7fjtfqn7zmtj --dst-port wasm.stars165fr5j3ea0dk5yr5sr4h8uw76z5fd34lpnqc2x80ya9xkx9u0k3qjrqpzq 2>&1 | jq`

But then trying to create a channel on existing client using `transact channel` isnt working:
`rly transact channel --override --log-format json -v ics721-1 junotestnet-stargazetestnet 2>&1 | jq`

Error:
```json
{
  "lvl": "info",
  "ts": "2023-09-19T14:40:14.562580Z",
  "msg": "Starting event processor for channel handshake",
  "src_chain_id": "uni-6",
  "src_port_id": "transfer",
  "dst_chain_id": "elgafar-1",
  "dst_port_id": "transfer"
}
{
  "lvl": "info",
  "ts": "2023-09-19T14:40:14.711819Z",
  "msg": "Chain is in sync",
  "chain_name": "junotestnet",
  "chain_id": "uni-6"
}
{
  "lvl": "info",
  "ts": "2023-09-19T14:40:15.200828Z",
  "msg": "Chain is in sync",
  "chain_name": "stargazetestnet",
  "chain_id": "elgafar-1"
}
{
  "lvl": "error",
  "ts": "2023-09-19T14:40:26.578967Z",
  "msg": "Error sending messages",
  "path_name": "junotestnet-stargazetestnet",
  "src_chain_id": "elgafar-1",
  "dst_chain_id": "uni-6",
  "src_client_id": "07-tendermint-566",
  "dst_client_id": "07-tendermint-598",
  "error": "rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 1: channel open init callback failed for port ID: transfer, channel ID: channel-698: got ics721-1, expected ics20-1: invalid ICS20 version [cosmos/ibc-go/v7@v7.2.0/modules/apps/transfer/ibc_module.go:84] With gas wanted: '100000000' and gas used: '143004' : unknown request"
}
{
  "lvl": "error",
  "ts": "2023-09-19T14:40:38.426228Z",
  "msg": {
    "type": "channel_open_init",
    "port_id": "transfer",
    "channel_id": "",
    "counterparty_port_id": "transfer",
    "counterparty_channel_id": "",
    "connection_id": "connection-713",
    "counterparty_connection_id": "",
    "order": "ORDER_UNORDERED",
    "version": "ics721-1"
  },
  "path_name": "junotestnet-stargazetestnet",
  "src_chain_id": "elgafar-1",
  "dst_chain_id": "uni-6",
  "src_client_id": "07-tendermint-566",
  "dst_client_id": "07-tendermint-598",
  "error": "rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 1: channel open init callback failed for port ID: transfer, channel ID: channel-698: got ics721-1, expected ics20-1: invalid ICS20 version [cosmos/ibc-go/v7@v7.2.0/modules/apps/transfer/ibc_module.go:84] With gas wanted: '100000000' and gas used: '146822' : unknown request"
}
```

Here my config.yaml:

```yaml
global:
    api-listen-addr: :5183
    timeout: 10s
    memo: Powered by Ark Protocol
    light-cache-size: 20
chains:
    junotestnet:
        type: cosmos
        value:
            key-directory: /home/ttruong/data/development/ics721-nodes/relayer/cosmos/keys/uni-6
            key: default
            chain-id: uni-6
            rpc-addr: https://rpc.uni.junonetwork.io:443
            account-prefix: juno
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.045ujunox
            min-gas-amount: 4500
            max-gas-amount: 800000
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    stargazetestnet:
        type: cosmos
        value:
            key-directory: /home/ttruong/data/development/ics721-nodes/relayer/cosmos/keys/elgafar-1
            key: default
            chain-id: elgafar-1
            rpc-addr: https://rpc.elgafar-1.stargaze-apis.com:443
            account-prefix: stars
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ustars
            min-gas-amount: 40000
            max-gas-amount: 800000
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    terra2testnet:
        type: cosmos
        value:
            key-directory: /home/ttruong/data/development/ics721-nodes/relayer/cosmos/keys/pisco-1
            key: default
            chain-id: pisco-1
            rpc-addr: https://terra-testnet-rpc.polkachu.com:443
            account-prefix: terra
            keyring-backend: test
            gas-adjustment: 1.3
            gas-prices: 0.15uluna
            min-gas-amount: 15000
            max-gas-amount: 800000
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 330
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    junotestnet-stargazetestnet:
        src:
            chain-id: uni-6
            client-id: 07-tendermint-598
            connection-id: connection-713
        dst:
            chain-id: elgafar-1
            client-id: 07-tendermint-566
            connection-id: connection-579
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-692
    junotestnet-terra2testnet:
        src:
            chain-id: uni-6
            client-id: 07-tendermint-597
            connection-id: connection-712
        dst:
            chain-id: pisco-1
            client-id: 07-tendermint-433
            connection-id: connection-394
        src-channel-filter:
            rule: ""
            channel-list:
                - channel-693
    stargazetestnet-terra2testnet:
        src:
            chain-id: elgafar-1
            client-id: 07-tendermint-565
            connection-id: connection-578
        dst:
            chain-id: pisco-1
            client-id: 07-tendermint-432
            connection-id: connection-393
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-572
```
