### ISSUE TITLE
for same path, channel with different client and connection possible?

### ISSUE THREAD

**Issue by taitruong** [cosmos/relayer#1311]
How does `client`, `connection` and `channel` related to each other? Like for this path example:
```yaml
paths:
    junotestnet-stargazetestnet:
        src:
            chain-id: uni-6
            client-id: 07-tendermint-629 # client CHANNEL_1_JUNO_TO_STARGAZE, target: 07-tendermint-584
            connection-id: connection-735 # connection CHANNEL_1_JUNO_TO_STARGAZE, target: connection-596
        dst:
            chain-id: elgafar-1
            client-id: 07-tendermint-584 # client CHANNEL_1_STARGAZE_TO_JUNO, target: 07-tendermint-629
            connection-id: connection-596 # connection CHANNEL_1_STARGAZE_TO_JUNO, target: connection-735
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-721 # channel CHANNEL_1_JUNO_TO_STARGAZE, target: channel-589
                - channel-726 # channel INTERCHAIN_WHITELIST_ADDRESSES_CHANNEL_1_JUNO_TO_STARGAZE, target: channel-594
```

What happens if I create a new channel with a new client and connection? So I'd have 2 channels in `config.yaml`. Seems like in config for each path only **ONE** client-id and connection-id can be configured.

Guess relayer would still relay both channels, but for what are client-id and connect-id used then? Was looking into this doc, but can't find much info about this: https://github.com/cosmos/relayer/blob/main/docs/create-path-across-chain.md
