### ISSUE TITLE
Relayer is not properly getting the lastest app state when executing handshake steps

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#300]
```
rly tx link cosmicslippers -d -o 3s 
I[2020-10-21|10:25:39.820] - [slippy-0] -> creating client (thestargate) for [stargate-4]header-height{91492} trust-period(336h0m0s) 
I[2020-10-21|10:25:44.224] ✔ [slippy-0]@{99288} - msg(0:create_client) hash(ED7014185BFE2810669B5AECC21AE8E569B8381787DCDB836280FEE0A012F576) 
I[2020-10-21|10:25:44.224] ★ Clients created: [slippy-0]client(thestargate) and [stargate-4]client(slipperland) 
I[2020-10-21|10:25:45.738] - [slippy-0]@{0}conn(cosmicslippers)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{0}conn(theslipperportal)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|10:25:49.226] ✔ [slippy-0]@{99289} - msg(0:connection_open_init) hash(A66AF9EC485F1A6AF2C67D6DFB8F545860B05DF9462CD91718FA5F8E35837938) 
I[2020-10-21|10:25:49.784] - [slippy-0]@{0}conn(cosmicslippers)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{0}conn(theslipperportal)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|10:25:49.792] - [slippy-0] -> sending transaction:         
E[2020-10-21|10:25:49.793] - [slippy-0] -> err(failed to execute message; message index: 0: connection handshake open init failed: cosmicslippers: connection already exists: invalid request) 
^C
```

When executing the connection handshake, the first attempt at INIT on the source chain succeeds as show above by the first set of steps:
```
rly tx link cosmicslippers -d -o 3s 
I[2020-10-21|10:25:39.820] - [slippy-0] -> creating client (thestargate) for [stargate-4]header-height{91492} trust-period(336h0m0s) 
I[2020-10-21|10:25:44.224] ✔ [slippy-0]@{99288} - msg(0:create_client) hash(ED7014185BFE2810669B5AECC21AE8E569B8381787DCDB836280FEE0A012F576) 
I[2020-10-21|10:25:44.224] ★ Clients created: [slippy-0]client(thestargate) and [stargate-4]client(slipperland) 
I[2020-10-21|10:25:45.738] - [slippy-0]@{0}conn(cosmicslippers)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{0}conn(theslipperportal)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|10:25:49.226] ✔ [slippy-0]@{99289} - msg(0:connection_open_init) hash(A66AF9EC485F1A6AF2C67D6DFB8F545860B05DF9462CD91718FA5F8E35837938) 
```

The first iteration of the for loop ends [here](https://github.com/ovrclk/relayer/blob/06740742e8e88baaff21efa5633c81a170d5ea24/relayer/connection-tx.go#L55)

Using the debug logs we can deduce that the second iteration of the for loop is executed in the exact same way as the first iteration. 

The next debug log shows:
```
I[2020-10-21|10:25:49.784] - [slippy-0]@{0}conn(cosmicslippers)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{0}conn(theslipperportal)-{STATE_UNINITIALIZED_UNSPECIFIED} 
```

This tells us both source and destination have uninitialized states. This is contradictory to the successful connection open init that occurred just before. The connection states [queried](https://github.com/ovrclk/relayer/blob/06740742e8e88baaff21efa5633c81a170d5ea24/relayer/connection-tx.go#L111) must be outdated resulting in execution of the same message twice. This gives us the expected result of:
```
E[2020-10-21|10:25:49.793] - [slippy-0] -> err(failed to execute message; message index: 0: connection handshake open init failed: cosmicslippers: connection already exists: invalid request) 
```

I can confirm the connection does exist
```
gaiad q ibc connection connections
connections:
- client_id: thestargate
  counterparty:
    client_id: slipperland
    connection_id: theslipperportal
    prefix:
      key_prefix: aWJj
  id: cosmicslippers
  state: STATE_INIT
  versions:
  - "\n\x011\x12\rORDER_ORDERED\x12\x0FORDER_UNORDERED"
height:
  version_height: "99345"
  version_number: "0"
pagination:
  next_key: null
  total: "0"
```

We need to ensure the light clients are updated to the latest possible states
