### ISSUE TITLE
Getting "failed to get trusted headers" error

### ISSUE THREAD

**Issue by orkunkl** [cosmos/relayer#373]
relayer version: 1.0.0-rc
I am trying to connect **musselnet-2** and **stargate-final** networks via IBC. this is the error I am getting at the moment:
```
rly tx link musselnet-2_stargate-final
I[2021-01-18|00:02:01.812] ★ Clients created: client(07-tendermint-0) on chain[musselnet-2] and client(07-tendermint-0) on chain[stargate-final]
I[2021-01-18|00:02:42.784] failed to get trusted headers: chain(stargate-final): post failed: Post "http://x.x.x.x:26657": EOF
I[2021-01-18|00:02:42.784] retrying transaction...
I[2021-01-18|00:05:22.766] failed to get trusted headers: chain(stargate-final): post failed: Post "http://x.x.x.x:26657": EOF
I[2021-01-18|00:05:22.766] retrying transaction...
I[2021-01-18|00:05:52.751] failed to get trusted headers: chain(stargate-final): post failed: Post "http://x.x.x.x:26657": EOF
I[2021-01-18|00:05:52.751] retrying transaction...
```

When I followed up the bug I found out this line is causing the error https://github.com/cosmos/relayer/blob/v1.0.0-rc1/relayer/headers.go#L122
which looks like might be related to this issue https://github.com/cosmos/cosmos-sdk/pull/8341

**Comment by colin-axner** [comment]
If the line you linked is causing the issue then it is probably because of [#8327](https://github.com/cosmos/cosmos-sdk/issues/8327). Looking at the error it seems to me there might be a connection issue (but the returned errors might just be deceiving). What parameters do you have set for historical entries in genesis? Those determine the length of time the relayer will support interacting with past events. The higher number of historical entries, the longer you can interact with past events

**Comment by orkunkl** [comment]
@colin-axner it is set to 10000 both in [musselnet genesis](https://rpc.musselnet.cosmwasm.com/genesis) and stargate-final-4

**Comment by colin-axner** [comment]
@orkunkl could you try checking out the branch `colin/test-upstream-fix`, it contains the 8327 and 8341 fixes. Would be good if we could rule those out as possible errors

**Comment by orkunkl** [comment]
Tried it with your branch.
```
rly version
version: 1.0.0-rc1-56-gfa0d02a
commit: fa0d02a07606798d3a67fe0306f20925f9d96835
cosmos-sdk: v0.40.0-rc7.0.20210118130753-646ea5545e2e
go: go1.15.6 linux/amd64
```
This is the error I am getting now which is different than before. I guess your branch fixed `EOF` error and now historical entries limit is not enough now. 
```
rly tx link new-path
I[2021-01-18|16:21:31.214] ★ Clients created: client(07-tendermint-0) on chain[musselnet-2] and client(07-tendermint-0) on chain[stargate-final]
I[2021-01-18|16:21:32.106] failed to get trusted headers: chain(musselnet-2): rpc error: code = NotFound desc = historical info for height 99443 not found: key not found
I[2021-01-18|16:21:32.106] retrying transaction...
```
So I have not run relayer from the beginning of the chain. What can I do to make it run now?

**Comment by colin-axner** [comment]
what is the current height of `musselnet-2`?

Go into `~/.relayer/config/config.yaml` and delete the client id's that have been set. Then rerun the `rly tx link` command

This will create new clients, which will rely on recent blocks. My guess is the clients currently created are older than the historical info in state, which results in this error.

**Comment by orkunkl** [comment]
```
/Workspace/relayer on colin/test-upstream-fix λ rly tx link new-path -d -o 3s
I[2021-01-18|18:59:13.063] ★ Clients created: client(07-tendermint-2) on chain[musselnet-2] and client(07-tendermint-2) on chain[stargate-final]
```
This command got stuck there for a while. What could be the reason?
```
~/.wasmd λ rly paths list
 1: new-path             -> chns(✔) clnts(✔) conn(✔) chan(✘) (musselnet-2:transfer<>stargate-final:transfer)
```

**Comment by colin-axner** [comment]
Did it work? I can only see that the clients were created. 

My guess is relayer had a hard time querying the chain. I believe it queries the chains for the `clnts` `conn` and `chan` to see if they are created

**Comment by jaybxyz** [comment]
@colin-axner I also confront this `failed to get trusted headers: chain(stargate-final): post failed: Post:...` error when I tried to link `bifrost-2` and `stargate-final` chains.

**Comment by jaybxyz** [comment]
I solved the issue by changing our full node pruning strategy to `nothing`

**Comment by colin-axner** [comment]
we should update the error message to indicate that the headers have likely been pruned

**Comment by orkunkl** [comment]
Updated wasmd to v0.14.1 and gaiad to v3.0.1 which both runs on cosmos-sdk 0.40.1, and relayer is on master (https://github.com/cosmos/relayer/commit/d9decfa7a4d49669e12aef5468b38d5fdf667647). Set `pruning` to `nothing` on both recently launched nodes. I ran the layer with this config file:
```yaml
global:
  timeout: 10s
  light-cache-size: 20
chains:
- key: testkey
  chain-id: musselnet-2
  rpc-addr: https://rpc-ibc.musselnet.cosmwasm.com:443
  account-prefix: wasm
  gas-adjustment: 1.1
  gas-prices: 0.01umayo
  trusting-period: 336h
- key: testkey
  chain-id: stargate-final
  rpc-addr: http://188.34.177.78:26657
  account-prefix: cosmos
  gas-adjustment: 1.3
  gas-prices: 0.01umuon
  trusting-period: 336h
paths:
  testpath:
    src:
      chain-id: musselnet-2
      client-id: 
      port-id: transfer
      order: ORDERED
      version: ics20-1
    dst:
      chain-id: stargate-final
      client-id:
      port-id: transfer
      order: ORDERED
      version: ics20-1
    strategy:
      type: naive
```

I am getting the same error: 
```
 rly tx link testpath -d -o 3s
I[2021-01-22|16:56:16.235] - [musselnet-2] -> creating client on musselnet-2 for stargate-final header-height{120236} trust-period(336h0m0s)
I[2021-01-22|16:56:16.596] - [stargate-final] -> creating client on stargate-final for musselnet-2 header-height{176352} trust-period(336h0m0s)
I[2021-01-22|16:56:16.972] ★ Clients created: client(07-tendermint-0) on chain[musselnet-2] and client(07-tendermint-0) on chain[stargate-final]
I[2021-01-22|16:56:18.156] failed to get trusted headers: chain(stargate-final): rpc error: code = NotFound desc = historical info for height 47056 not found: key not found
I[2021-01-22|16:56:18.156] retrying transaction...
I[2021-01-22|16:56:24.102] failed to get trusted headers: chain(stargate-final): rpc error: code = NotFound desc = historical info for height 47056 not found: key not found
I[2021-01-22|16:56:24.102] retrying transaction...
I[2021-01-22|16:56:29.904] failed to get trusted headers: chain(musselnet-2): rpc error: code = NotFound desc = historical info for height 99443 not found: key not found
I[2021-01-22|16:56:29.904] retrying transaction...
I[2021-01-22|16:56:35.803] failed to get trusted headers: chain(stargate-final): rpc error: code = NotFound desc = historical info for height 47056 not found: key not found
I[2021-01-22|16:56:35.803] retrying transaction...
Error: ! Connection failed: [musselnet-2]client{07-tendermint-0}conn{} -> [stargate-final]client{07-tendermint-0}conn{}
```

**Comment by orkunkl** [comment]
Updated wasmd to `v0.14.1` (runs cosmos-sdk v0.40.1) and gaiad to `v3.0.1`. Set `pruning` option to `nothing` and launched bare new nodes. relayer is running on master(https://github.com/cosmos/relayer/commit/d9decfa7a4d49669e12aef5468b38d5fdf667647)
Here is the relayer config:
```yaml
global:
  timeout: 10s
  light-cache-size: 20
chains:
- key: testkey
  chain-id: musselnet-2
  rpc-addr: https://rpc-ibc.musselnet.cosmwasm.com:443
  account-prefix: wasm
  gas-adjustment: 1.1
  gas-prices: 0.01umayo
  trusting-period: 336h
- key: testkey
  chain-id: stargate-final
  rpc-addr: http://188.34.177.78:26657
  account-prefix: cosmos
  gas-adjustment: 1.3
  gas-prices: 0.01umuon
  trusting-period: 336h
paths:
  testpath:
    src:
      chain-id: musselnet-2
      client-id: 
      port-id: transfer
      order: ORDERED
      version: ics20-1
    dst:
      chain-id: stargate-final
      client-id:
      port-id: transfer
      order: ORDERED
      version: ics20-1
    strategy:
      type: naive
```
I am getting the same error when linking:
```
rly tx link testpath -d -o 3s
I[2021-01-22|16:56:16.235] - [musselnet-2] -> creating client on musselnet-2 for stargate-final header-height{120236} trust-period(336h0m0s)
I[2021-01-22|16:56:16.596] - [stargate-final] -> creating client on stargate-final for musselnet-2 header-height{176352} trust-period(336h0m0s)
I[2021-01-22|16:56:16.972] ★ Clients created: client(07-tendermint-0) on chain[musselnet-2] and client(07-tendermint-0) on chain[stargate-final]
I[2021-01-22|16:56:18.156] failed to get trusted headers: chain(stargate-final): rpc error: code = NotFound desc = historical info for height 47056 not found: key not found
I[2021-01-22|16:56:18.156] retrying transaction...
I[2021-01-22|16:56:24.102] failed to get trusted headers: chain(stargate-final): rpc error: code = NotFound desc = historical info for height 47056 not found: key not found
I[2021-01-22|16:56:24.102] retrying transaction...
I[2021-01-22|16:56:29.904] failed to get trusted headers: chain(musselnet-2): rpc error: code = NotFound desc = historical info for height 99443 not found: key not found
I[2021-01-22|16:56:29.904] retrying transaction...
I[2021-01-22|16:56:35.803] failed to get trusted headers: chain(stargate-final): rpc error: code = NotFound desc = historical info for height 47056 not found: key not found
I[2021-01-22|16:56:35.803] retrying transaction...
Error: ! Connection failed: [musselnet-2]client{07-tendermint-0}conn{} -> [stargate-final]client{07-tendermint-0}conn{}
```
