### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by Red-Blink** [cosmos/relayer#591]
## Description
The relayer will return a bad handshake error when trying to connect to secure websockets. This happens because the chain config specifies the rpc-addr as https.

## Relayer Version
1.0.0

## Error Message
websocket: bad handshake

## Config.yaml
```
global:
  api-listen-addr: :5183
  timeout: 30s
  light-cache-size: 20
chains:
- key: terra-key
  chain-id: columbus-5
  rpc-addr: http://127.0.0.1:26657
  account-prefix: terra
  gas-adjustment: 1.4
  gas-prices: 0.15uluna
  trusting-period: 48h
- key: osmosis-key
  chain-id: osmosis-1
  rpc-addr: https://osmosis-rpc.quickapi.com:443
  account-prefix: osmo
  gas-adjustment: 1.4
  gas-prices: 0.0025uosmo
  trusting-period: 48h
paths:
  transfer:
    src:
      chain-id: columbus-5
      client-id: 07-tendermint-12
      connection-id: connection-47
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    dst:
      chain-id: osmosis-1
      client-id: 07-tendermint-1870
      port-id: transfer
      order: UNORDERED
      version: ics20-1
```

## How to Produce
rly start transfer

## Notes
I am attempting this relay on a Terra Validator and wish to connect it to Osmosis blockchain.
