### ISSUE TITLE
Non-descriptive error when starting relayer.

### ISSUE THREAD

**Issue by kevinroleke** [cosmos/relayer#600]
I am trying to setup a relayer between the Osmosis testnet (osmo-test-4) and my early-development testnet. 

Here are the chain configurations:

```json
{
  "type": "cosmos",
  "value": {
      "key": "mykey",
      "chain-id": "tiso-1",
      "rpc-addr": "http://127.0.0.1:26657",
      "grpc-addr": "http://127.0.0.1:9999",
      "account-prefix": "tiso",
      "keyring-backend": "test",
      "gas-adjustment": 1.3,
      "gas-prices": "0.025tis",
      "debug": true,
      "timeout": "10s",
      "output-format": "json",
      "sign-mode": "direct"
 }
}
```

```json
{
  "type": "cosmos",
  "value": {
      "key": "mykey_osmosis",
      "chain-id": "osmo-test-4",
      "rpc-addr": "http://127.0.0.1:26660",
      "grpc-addr": "http://127.0.0.1:9998",
      "account-prefix": "osmo",
      "keyring-backend": "test",
      "gas-adjustment": 1.3,
      "gas-prices": "0.025uosmox",
      "debug": true,
      "timeout": "10s",
      "output-format": "json",
      "sign-mode": "direct"
 }
}
```

I added them to the relayer and "successfully" generated a path between the two.

```yaml
path:
  src:
    chain-id: tiso-1
    port-id: transfer
    order: UNORDERED
    version: ics20-1
  dst:
    chain-id: osmo-test-4
    port-id: transfer
    order: UNORDERED
    version: ics20-1
  strategy:
    type: naive
status:
  chains: true
  clients: false
  connection: false
  channel: false

```

However, upon starting the relayer, I am always met with this non-descriptive error.

```
I[2022-03-17|19:59:07.558] - listening to tx events from tiso-1...    
I[2022-03-17|19:59:07.558] - listening to block events from tiso-1... 
I[2022-03-17|19:59:07.559] - listening to tx events from osmo-test-4... 
I[2022-03-17|19:59:07.559] - listening to block events from osmo-test-4... 
Error: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = identifier cannot be blank: invalid identifier: invalid request
```

After googling around, I couldn't find anyone with this same problem :( 

How can I get a better idea at what exactly is wrong here? 

Thanks
