### ISSUE TITLE
Proposal: Config Update to accommodate path channel filtering

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#601]
As we move the relayer into relaying on all channels on a given connection, we need to introduce a whitelist OR blacklist to filter desired or undesired channels to relay over.

Proposal:
See: `channel-filter`
```yaml
paths:
    demo:
        src:
            chain-id: ibc-0
            client-id: 07-tendermint-0
            connection-id: connection-0
            channel-filter:
                whitelist: [('transfer', 'channel-0'), ('transfer', 'channel-3')]
        dst:
            chain-id: ibc-1
            client-id: 07-tendermint-0
            connection-id: connection-0
```

After briefly discussing with @jtieri, we should only allow EITHER "whitelist" OR "blacklist", NOT both, which would throw an error.
