### ISSUE TITLE
Account for changes in channel state

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#858]
In interchain accounts, if a packet times out, then the channel end moves to a `CLOSED` state and the channel will need to be re-opened.

Currently we handle the timing out part correctly but I believe we need to update the state for the channel at that point. Right now if we time out a packet on an `ORDERED` channel with the relayer we will see the packet timeout correctly and can observe that the one end of the channel becomes `CLOSED` but we don't handle the re-opening of said channel correctly. Essentially you will see logs like this:
```
ts=2022-07-19T20:00:55.774868Z lvl=info msg="Error building or broadcasting transaction" provider_type=cosmos chain_id=test-2 attempt=1 max_attempts=5 error="rpc error: code = InvalidArgument desc = failed to execute message; message index: 1: channel open try callback failed: existing active channel channel-0 for portID icahost is already OPEN: active channel already set for this owner: invalid request"
```

Upon manually querying the channel state you can verify that it is closed:
```
channels:
- channel_id: channel-0
  connection_hops:
  - connection-0
  counterparty:
    channel_id: channel-0
    port_id: icahost
  ordering: ORDER_ORDERED
  port_id: icacontroller-cosmos1m9l358xunhhwds0568za49mzhvuxx9uxre5tud
  state: STATE_CLOSED
  version: '{"version":"ics27-1","controller_connection_id":"connection-0","host_connection_id":"connection-0","address":"cosmos15ccshhmp0gsx29qpqq6g4zmltnnvgmyu9ueuadh9y2nc5zj0szls5gtddz","encoding":"proto3","tx_type":"sdk_multi_msg"}'
height:
  revision_height: "175"
  revision_number: "1"
pagination:
  next_key: null
  total: "0"
```

To reproduce the issue:
- Checkout main branch on the relayer and `make install`
- Clone down the ICA demo repo here https://github.com/jtieri/interchain-accounts-demo 
- Run `make init-golang-rly` from the root directory of the ICA demo repo

NOTE: relayer output is redirected to `./data/rly-0.log`
