### ISSUE TITLE
--override doesn't seem to be wired up correctly when creating clients

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#952]
`rly tx clients <path>` is supposed to create a new client on both chains. HOWEVER if you have if you already have a client-id in your config associated with that path, the command will not create a new client.

For example if you config looks like:
```yaml
paths:
    demopath:
        src:
            chain-id: ibc-0
            client-id: 07-tendermint-0
        dst:
            chain-id: ibc-1
            client-id: 07-tendermint-0
        src-channel-filter:
            rule: ""
            channel-list: []
```
And you run 
`rly tx clients demopath`
A new client is **not** created. 

AFAIK the `--override` flag is supposed to override you config and create a new client.
This does not work. 

The only way to create a new client is to remove the client-id from your config and re-run command (--override flag is not necessary):
```yaml
paths:
    demo:
        src:
            chain-id: ibc-0
        dst:
            chain-id: ibc-1
        src-channel-filter:
            rule: ""
            channel-list: []
```

This is posing issues for client related tests in `ibctest`
